from lvis_config import IMAGE_BUCKET, IMAGE_LIST_PATH, DEMO_IMAGES

N_RESULTS_TO_DISPLAY = 50
N_CONCURRENT_WORKERS_DEFAULT = 350

HANDLER_URL = "https://knn-wj4n6yaj3q-uc.a.run.app"
TEMPLATE_ENDPOINT = f"{HANDLER_URL}/template"
QUERY_ENDPOINT = f"{HANDLER_URL}/score"

IMAGE_URL_PREFIX = f"{IMAGE_BUCKET}/"
OUTPUT_BUCKET = IMAGE_BUCKET

QUERY_CLEANUP_TIME = 60 * 60  # seconds
